package io.naadf.bevy;

import android.view.View;

import com.google.androidgamesdk.GameActivity;

// Mirrors Bevy's `examples/mobile/android_example/.../MainActivity.java`.
// The static block loads `libbevy_naadf.so` (built by `cargo ndk` into
// `android/app/src/main/jniLibs/arm64-v8a/`) before GameActivity hands off to
// the Rust `android_main` symbol generated by Bevy's `#[bevy_main]` macro
// (see `crates/bevy_naadf/src/android_main.rs`).
public class MainActivity extends GameActivity {
    static {
        System.loadLibrary("bevy_naadf");
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus) {
            hideSystemUi();
        }
    }

    private void hideSystemUi() {
        View decorView = getWindow().getDecorView();
        decorView.setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                        | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_FULLSCREEN
        );
    }
}
